version: '3.1'

services:
  db:
    image: mysql:5.6
    command: "mysqld --character-set-server=utf8 --collation-server=utf8_general_ci"
    restart: always
    environment:
      MYSQL_USER: siri
      MYSQL_PASSWORD: siri123
      MYSQL_ROOT_PASSWORD: Admin123
      MYSQL_DATABASE: org
    ports:
      - 3306:3306